# Generated by Django 5.2.3 on 2025-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
