# Generated by Django 5.2.3 on 2025-07-05 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexapp", "0003_upcomingevents"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("title", models.CharField(max_length=100)),
                ("course_id", models.CharField(max_length=100)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="indexapp.team"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Latest Courses",
            },
        ),
    ]
